#name: CI Build
#env:
#    OUTPUT_PATH: ${{ github.workspace }}/.output
#    DOTNET_VERSION: "3.1.100"
#    
#on:
#  push:
#    branches: [ develop ]
#
#jobs:
#  package:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout 🛎️
#      uses: actions/checkout@v2
#    - name: Setup .NET Core ${{ env.DOTNET_VERSION }} 🔧
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: ${{ env.DOTNET_VERSION }}
#    - name: Install dependencies 🔧
#      run: dotnet restore
#    - name: Build 🔨
#      run: dotnet build --configuration Release --no-restore --output ${{ env.OUTPUT_PATH }}
#    - name: Upload Package 📦
#      uses: actions/upload-artifact@v1
#      with:
#        name: DurableFunction
#        path: ${{ env.OUTPUT_PATH }}
#        
#  deploy-to-qa:
#    env:
#      RESOURCE_GROUP: "gw-icap-qa"
#      FUNC_APP_NAME: durablefileprocessing-qa
#    runs-on: ubuntu-latest
#    needs: [package]
#    steps:
#    - name: Checkout 🛎️
#      uses: actions/checkout@v2
#    - name: Download package 📦
#      uses: actions/download-artifact@v1
#      with:
#        path: ${{ env.OUTPUT_PATH }}
#        name: DurableFunction
#    - name: Azure Login 🔑
#      uses: Azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
#    - name: Deploy ARM Template 🚀
#      uses: Azure/cli@v1.0.0
#      with:
#        inlineScript: az group deployment create --name template --resource-group ${{ env.RESOURCE_GROUP }} --template-file ${{ env.OUTPUT_PATH }}/Setup/template.json
#    - name: Overwrite App Settings 📝
#      uses: cschleiden/replace-tokens@v1
#      with:
#        tokenPrefix: '--'
#        tokenSuffix: '--'
#        files: 'serverless.yml'
#      env:
#        REBUILD_KEY: ${{ secrets.QA_REBUILD_API_KEY }}
#        FILETYPEDETECTION_KEY: ${{ secrets.QA_FILEYPEDETECTION_API_KEY }}
#        STORAGE_ACCOUNT_CONNECTION_STRING: $ {{ secrets.QA_STORAGE_CONNECTION_STRING }}
#        SERVICE_BUS_CONNECTION_STRING: ${{ secrets.SERVICEBUS_CONNECTION_STRING }}
#    - name: Setup Node 🔧
#      uses: actions/setup-node@v1
#      with:
#        node-version: '10.x'
#    - name: NPM Install 🔧
#      run: npm install
#    - name: NPM Install Dependencies 🔧
#      run: npm i serverless-azure-functions   
#    - name: Serverless Deploy 🚀
#      uses: aaronpanch/action-serverless@v1.0.0
#      with:
#        args: deploy
#
